targets:
  OBAKitCore:
    type: framework
    platform: [iOS, watchOS]
    sources: ["."]
    dependencies:
      - package: CocoaLumberjack
      - package: CocoaLumberjackSwift
      - package: SwiftProtobuf
    scheme:
      gatherCoverageData: true
    info:
      path: "Info.plist"
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: true
